export { default as Website } from './_website'
export { default as Scroll } from './_scroll'
// export { default as Axeptio } from '../modules/_axeptio'
// export { default as Menu } from './_menu'
// export { default as Slider } from './_slider'
// export { default as Accordeon } from './_accordeon'
// export { default as Form } from './_form'
// export { default as Popin } from './_popin'
// export { default as Button } from './_button'
// export { default as Ajax } from './_ajax'
// export { default as Styleguide } from './_styleguide'
export { default as Test } from './_test'
